import AboutSection from "@/components/AboutSection"
import HeroSection from "@/components/HeroSection"
import ProjectsSection from "@/components/ProjectsSection"
import Head from "next/head"
import { ThemeProvider } from "next-themes"
import Navbar from "@/components/Navbar"
import Footer from "@/components/Footer"
export default function Home() {
  return (
    <>
      <Head>
        <title>Sumit Verma</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>👋</text></svg>"
        />
      </Head>
      <body className="dark:bg-stone-900">
        <ThemeProvider enableSystem={true} attribute="class">
          <main className="mx-auto max-w-3xl px-4 sm:px-6 md:max-w-5xl ">

            <Navbar />
            <HeroSection />
            <AboutSection />
            <ProjectsSection />
            <Footer />

          </main>
        </ThemeProvider>
      </body>
    </>
  )
}
